### ISSUE TITLE
Download Function Date - Broken. 

### ISSUE THREAD

**Issue by minorsecond** [shdcn/easygentoo#4]
Get an error when script tries to download tarball - apparently there is a mismatch between the date the download function uses and the tarball date. Manually entered name of tarball (stage3-amd64-20140508.tar.bz2" in the line:

lnk="${tarballurl}/${date}/stage3-amd64-20140508.tar.bz2"; arg="1"

and it functions correctly.

**Comment by 4L3Xx** [comment]
Can confirm, I could not even get it to work with your suggestion (hash mismatch).

Looks like get_tarball function might be broken.

**Comment by minorsecond** [comment]
@4L3Xx , I haven't run this script in some time. Do you remember the error message that resulted from this bug? I'm going to get a VM set up later so I can test.

**Comment by 4L3Xx** [comment]
It just loops forever through the mirrors, saying that it failed to download from a mirror and that its going to try another mirror.  I believe it is trying to download the stage3 tarball.

**Comment by minorsecond** [comment]
That's right. I remember now. I should have been more detailed in my bug
report.

**Comment by chsinlmu** [comment]
the get_tarball function (starting at line 1328) seems to be broken. If commenting out the while loop and manually setting the date and tarball variables the script seems to work:
```bash
get_tarball() {
    echo; eb2 "* "; eg "Getting latest tarball name..."; sleep 0.5s
    
    [[ -e "${lt}" ]] && rm -rf ${lt}
    download "latest"
    
    #while read lt_line
    #do
    #    if [ "${lt_line}" != "^#*" ]; then
    #        date="${lt_line:0:8}"
    #        [[ "${lt_line}" == "${date}/stage3-${arch}-${date}.tar.bz2" ]] && tarball="stage3-${arch}-${date}.tar.bz2" && break
    #    fi
    #done < "${lt}"
    date="20150423"
    tarball="stage3-${arch}-${date}.tar.bz2"
    ...
```
below the while loop. Maybe this helps debugging.

**Comment by shdcn** [comment]
Sorry for delay, I am working on this issue right now. Looks like something has changed in latest-stage3.txt file or server directory layouts. Hope I will fix this today.

**Comment by shdcn** [comment]
Looks like likewhoa already fixed it :) Thanks.
